# Load in Numpy

In [1]:
import numpy as np

# Basics

In [2]:
a = np.array([1,2,3],dtype='int32')

a

array([1, 2, 3])

In [3]:
b = np.array([[1.0,2.0,3.0],[5.0,6.0,7.0]])

b

array([[1., 2., 3.],
       [5., 6., 7.]])

In [4]:
# get number of dimension

#a.ndim
b.ndim

2

In [5]:
b.shape

(2, 3)

In [6]:
# get type

a.dtype

dtype('int32')

In [7]:
# get size

a.itemsize

4

In [8]:
# get total sizes

a.nbytes

12

# Changing specific row,element,column etc

In [9]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
a.shape

(2, 7)

In [11]:
# get a specific element [r,c]

a[1,5]
#a[1,-2]

13

In [12]:
# get a specific row

a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get a specific column

a[:,2]

array([ 3, 10])

In [14]:
# getting a little more fancy [startindex:endindex:stepsize]

a[0,1:6:2]

array([2, 4, 6])

In [15]:
#change element

a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [16]:
#a[:,2] = 5
a[:,2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [17]:
#3d example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# get a specific element (work outside in)

b[0,1,1]

4

In [19]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [20]:
b[:,1,:] = [[9,9],[8,8]]

b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initialize different type of array

In [21]:
# all 0s matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# all 1s matrix

np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
# any other number

np.full((2,3),22)

array([[22, 22, 22],
       [22, 22, 22]])

In [24]:
# any other number (full-like method)

np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [25]:
# random decimal number

np.random.rand(4,2)

array([[0.42464204, 0.78978104],
       [0.47574771, 0.6499931 ],
       [0.91387307, 0.55472812],
       [0.17220898, 0.76747928]])

In [26]:
np.random.random_sample(a.shape)

array([[0.12361377, 0.44882165, 0.85253928, 0.52703198, 0.84395275,
        0.89757895, 0.20288137],
       [0.42548682, 0.05843336, 0.98257166, 0.86643601, 0.75668231,
        0.48613009, 0.63124276]])

In [27]:
# random integer value

#np.random.randint(8,size=(2,3))
np.random.randint(2,9,size=(2,3))

array([[5, 3, 7],
       [3, 3, 3]])

In [28]:
# the identity matrix

np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [29]:
# repeat an array

arr = np.array([[1,2,3]])
arr1 = np.repeat(arr,3,axis=0)

arr1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
output = np.ones((5,5))
output



array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
zero = np.zeros((3,3))

zero[1,1] = 9

zero

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [32]:
output[1:4,1:4] = zero

output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# be careful when copying array

In [33]:
a = np.array([1,2,3])
b=a.copy()
b[0] = 100
a

array([1, 2, 3])

# Mathematics

In [34]:
math1 = np.array([1,2,3])

math1

array([1, 2, 3])

In [35]:
math1 + 2

array([3, 4, 5])

In [36]:
math1 - 2

array([-1,  0,  1])

In [37]:
math1 * 2

array([2, 4, 6])

In [38]:
math1/2

array([0.5, 1. , 1.5])

In [39]:
math2 = np.array([0,1,0])
math2

array([0, 1, 0])

In [40]:
math1 + math2

array([1, 3, 3])

In [41]:
a ** 2

array([1, 4, 9], dtype=int32)

In [42]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# LINEAR ALGEBRA

In [43]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [44]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [45]:
c = np.identity(3)


np.linalg.det(c)

1.0

## statistics

In [46]:
stats = np.array([[1,2,3],[4,5,6]])

stats


array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.min(stats)

1

In [48]:
np.max(stats,axis=1)

array([3, 6])

# reorganizing arrays

In [49]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(4,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [50]:
# vertical stacking vector

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# horizontal stack

In [51]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellanous

## load data from file

In [53]:
filedata = np.genfromtxt('data.txt',delimiter=',')

filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

# Boolean masking and advanced indexing

In [55]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [56]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [57]:
#You can index with a list in numpy

In [58]:
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,3,8]]

array([2, 4, 9])

In [60]:
np.all(filedata > 50 , axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [61]:
np.any(filedata > 50 , axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [62]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [63]:
# not
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])